config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :messages do
    resources :comments
  end
  root "messages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_message
    before_action :find_comment, only:[:edit,:update,:destroy]
    before_action :authenticate_user!

    def create

        @comment=@message.comments.create(comment_params)
        @comment.user_id=current_user.id

        if @comment.save
            redirect_to message_path(@message)
        else
            render 'new' 
        end
    end


    def edit

    end

    def update
        if @comment.update(comment_params)
            redirect_to message_path(@message,@comment)
        else
            render 'edit'
        end
        
    end

    def destroy
        @comment.destroy
        redirect_to message_path(@message)
    end

    private
    
    def comment_params
        params.require(:comment).permit(:content)
    end

    def find_message
        @message=Message.find(params[:message_id])
    end

    def find_comment
        @comment=@message.comments.find(params[:id])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :find_message, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!,except: [:index,:show]

    def index
        @messages=Message.all.order("created_at DESC")
    end

    def new
        @message=current_user.messages.build
    end

    def create
        @message=current_user.messages.build(message_params)
        if @message.save
            redirect_to root_path
        else
            render 'new' 
        end
    end

    def edit 
    end

    def update
        if @message.update(message_params)
            redirect_to message_path(@message)
        else 
            render "edit"
        end
    end

    def destroy
        @message.destroy
        redirect_to root_path
    end



    private
     def message_params
        params.require(:message).permit(:title,:description)
     end

     def find_message
        @message=Message.find(params[:id])
     end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<p>
    <%= comment.content %>
</p>
<p>Posted by <%= comment.user.email %> <%=time_ago_in_words(comment.created_at) %> </p>
<% if user_signed_in? %>
    <% if comment.user_id == current_user.id %>
      <%= link_to 'Edit', edit_message_comment_path(comment.message,comment) %>
      <%= link_to 'Delete', message_comment_path(comment.message,comment) ,method: :delete,data:{confirm:"Are You sure ?"} %>
    <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for([@message,@message.comments.build])  do |f| %>

<%= f.input :content, label: "Comment" %>
<%= f.button :submit %>

<% end %>

app/views/comments/edit.html.erb
<div class="col-md-8 col-md-offset-2 mt-2">

<h2>Edit Comment</h2>
<%= simple_form_for([@message,@comment]) do |f| %>
    <%= f.input :content, label: "Comment" %>
    <%= f.button :submit ,class: "btn btn-primary"%>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageBord</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <div class="container">
    <%= link_to 'Message Bord', root_path ,class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
             <%= link_to 'Home', root_path ,class: "nav-link"%>
          </li>
      
        </ul>
        <ul class="nav navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'new Message', new_message_path,class: "nav-link" %>
            </li>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path ,method: :delete,class: "nav-link"%>
          </li>
        <% else %>
               <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path ,class: "nav-link"%>
          </li>
              <li class="nav-item">
            <%= link_to 'Login', new_user_session_path ,class: "nav-link" %>
          </li>
        <% end %>
     
        </ul>
        
        </nav>
    
        </div>
      </div>
       
    </nav>
    <div class="container">
       <% if notice %>
           <p class="alert alert-info mt-2"><%= notice %></p>
       <% end %>
     <% if alert %>
       <p class="alert alert-danger mt-2"><%= alert %></p>
     <% end %>
       
        <%= yield %>
    </div>

  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
    <%= f.input :title ,label: "Message Title"%>
    <%= f.input :description %>
    <%= f.submit class: "btn btn-primary"%>

<% end %>

app/views/messages/edit.html.erb
<div class="col-md-8 col-md-offset-2 mt-2">

<h2>Edit Message</h2>
<%= render "form" %>
</div>

app/views/messages/index.html.erb
<div class="row mt-3">
<% @messages.each do |message| %>
    <div class="col-md-4">
        <div class="card bg-dark text-white">
        <div class="card-body">
            <h4 class="card-title">Message</h4>
            <h6 class="card-subtitle mb-2 text-success"><%=message.title %></h6>
            <p class="card-text"><%=message.description %></p>
            <%= link_to 'show', message_path(message),class: "btn btn-info" %>
        </div>
        </div>
    </div>
<% end %>
</div>

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2 mt-2">

<h2>New Message </h2>

<%= render "form" %>
</div>

app/views/messages/show.html.erb
<div class="col-md-8 col-md-offset-2 mt-2">

<h2>Show Message</h2>
<h2>Title: <%= @message.title %> </h2>
<p>Posted by <%= @message.user.try(:email) %>  <%=time_ago_in_words(@message.created_at) %> </p>
<p>
 <%= @message.description %>
</p>
<h3>Comments :</h3>
<%= render @message.comments %>

<h3>Reply to message :</h3>
<p>
<% if user_signed_in? %>
<%= render 'comments/form' %>
<% end %>
</p>


<% if user_signed_in? %>
     <% if @message.user_id==current_user.id %>
            <%= link_to 'Edit', edit_message_path(@message),class: "btn btn-warning" %>
               <%= link_to 'Delete', message_path(@message),class: "btn btn-danger" ,method: :delete,data:{confirm: "Are You sure "}%>
     <% end %>
<% end %>
<%= link_to 'back', root_path,class: "btn btn-primary" %>

</div>